Attempting to solve the business issue of:<br>

What are the indicators of depression, anxiety or stress among the respondents?<br>

By using sample test:

Importing dataset:

In [1]:
import pandas as pd
from scipy.stats import ttest_rel

In [2]:
# Read file using pandas
df = pd.read_csv('modified_dataset.csv')
df

,Q1A,Q1I,Q2A,Q2I,Q3A,Q3I,Q4A,Q4I,Q5A,Q5I,...,voted,married,familysize,major,depression_scores,anxiety_scores,stress_scores,depression_status,anxiety_status,stress_status
0,4,28,4,25,2,16,4,8,4,34,...,2,1,2,Unknown,41,48,54,Extremely Severe,Extremely Severe,Extremely Severe
1,4,2,1,36,2,35,3,28,4,10,...,2,1,4,Unknown,38,31,41,Extremely Severe,Extremely Severe,Extremely Severe
2,3,7,1,33,4,41,1,13,4,11,...,1,1,3,Unknown,53,26,31,Extremely Severe,Extremely Severe,Severe
3,2,23,3,11,2,37,1,27,3,28,...,2,1,5,biology,30,31,30,Extremely Severe,Extremely Severe,Severe
4,2,36,2,13,3,5,4,10,4,2,...,2,1,4,Psychology,46,54,43,Extremely Severe,Extremely Severe,Extremely Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39770,2,31,1,5,3,29,2,37,3,39,...,2,1,2,Unknown,50,26,29,Extremely Severe,Extremely Severe,Severe
39771,3,14,4,41,3,15,4,33,3,17,...,2,1,4,Mathematic,52,48,48,Extremely Severe,Extremely Severe,Extremely Severe
39772,2,1,1,4,2,14,1,27,1,6,...,1,2,3,Computer Science,18,15,19,Moderate,Severe,Moderate
39773,3,36,1,34,2,10,2,20,3,9,...,1,1,2,History,30,27,47,Extremely Severe,Extremely Severe,Extremely Severe
39774,2,28,1,22,2,4,1,19,4,32,...,1,1,4,Cognitive Science,41,24,30,Extremely Severe,Extremely Severe,Severe

In [7]:
data = df[["depression_scores","anxiety_scores","stress_scores","depression_status","anxiety_status","stress_status"]]
print(data)

       depression_scores  anxiety_scores  stress_scores depression_status  \
0                     41              48             54  Extremely Severe
1                     38              31             41  Extremely Severe
2                     53              26             31  Extremely Severe
3                     30              31             30  Extremely Severe
4                     46              54             43  Extremely Severe
...                  ...             ...            ...               ...
39770                 50              26             29  Extremely Severe
39771                 52              48             48  Extremely Severe
39772                 18              15             19          Moderate
39773                 30              27             47  Extremely Severe
39774                 41              24             30  Extremely Severe

         anxiety_status     stress_status
0      Extremely Severe  Extremely Severe
1      Extremely Severe  Extremely Severe
2      Extremely Severe            Severe
3      Extremely Severe            Severe
4      Extremely Severe  Extremely Severe
...                 ...               ...
39770  Extremely Severe            Severe
39771  Extremely Severe  Extremely Severe
39772            Severe          Moderate
39773  Extremely Severe  Extremely Severe
39774  Extremely Severe            Severe

[39775 rows x 6 columns]

In [6]:
#Dependent sample t-test
#the means of two related groups to determine whether there is a statistically significant difference between these means.
#comparing depression scores and anxiety scores 
a = df['depression_scores']
b = df['anxiety_scores']
t, p = ttest_rel(a, b)
print('t-statistic: ', t)
print('p-value: ', p)
print('Since the p-value is less than 0.05, reject null hypothesis')
print('Conclusion: There is a significant different in mean between depression scores and anxiety scores.')

t-statistic:  106.58653388646765
p-value:  0.0
Since the p-value is less than 0.05, reject null hypothesis
Conclusion: There is a significant different in mean between depression scores and anxiety scores.

In [8]:
#comparing depression scores and stress scores 

a = df['depression_scores']
b = df['stress_scores']
t, p = ttest_rel(a, b)
print('t-statistic: ', t)
print('p-value: ', p)
print('Since the p-value is less than 0.05, reject null hypothesis')
print('Conclusion: There is a significant different in mean between depression scores and stress scores.')

t-statistic:  -2.225115301959094
p-value:  0.026079085006395854
Since the p-value is less than 0.05, reject null hypothesis
Conclusion: There is a significant different in mean between depression scores and stress scores.

In [9]:
#comparing anxiety scores and stress scores 

a = df['anxiety_scores']
b = df['stress_scores']
t, p = ttest_rel(a, b)
print('t-statistic: ', t)
print('p-value: ', p)
print('Since the p-value is less than 0.05, reject null hypothesis')
print('Conclusion: There is a significant different in mean between anxiety scores and stress scores.')

t-statistic:  -155.62101565117183
p-value:  0.0
Since the p-value is less than 0.05, reject null hypothesis
Conclusion: There is a significant different in mean between anxiety scores and stress scores.